### PR TITLE
WIP:  Lightweight version of `ark-circom`

### PR DESCRIPTION
**Pull request by tyshko-rostyslav**
WIP PR towards https://github.com/gakonst/ark-circom/issues/40

As `zerokit` is trying to reduce it's binaries' sizes, we'd like a lightweight version of `ark-circom` to be introduced. That means without the ethers-core/ethers-rs dependencies.
https://github.com/vacp2p/zerokit/issues/37

### CODE REVIEW

**Review by gakonst — CHANGES_REQUESTED** [review]
Let's keep the file and feature flag it along with the ethers dependency instead

**Comment by tyshko-rostyslav** [comment]
> Let's keep the file and feature flag it along with the ethers dependency instead

Sure, working on it

**Comment by tyshko-rostyslav** [comment]
@gakonst Could you, please, take a look? If there are no other issues, could you merge it?

**Review by gakonst — APPROVED** [review]

**Comment by gakonst** [comment]
merged + fixed my nits here https://github.com/gakonst/ark-circom/commit/746d2329e94e493560a53c41938c329d735d54ed

**Comment by tyshko-rostyslav** [comment]
> merged + fixed my nits here [746d232](https://github.com/gakonst/ark-circom/commit/746d2329e94e493560a53c41938c329d735d54ed) - thank you!!

@gakonst  Could we make `ethers` optional, as in my PR?

**Comment by tyshko-rostyslav** [comment]
@gakonst Could you fix the https://github.com/gakonst/ark-circom/blob/746d2329e94e493560a53c41938c329d735d54ed/src/lib.rs#L10 `full` feature to `ethereum`, so that CI passes and the code builds?

**Comment by gakonst** [comment]
done!

**Pull request merged**
