### PR TITLE
circom2 proof generation

### PR DESCRIPTION
**Pull request by philsippl**
Continuing #10 
Circom2 groth16 proof generation is now working, implemented a few missing functions from the spec [here](https://docs.google.com/document/d/1P0j9zXjJRkhnyPT03VjxYBUySC8l4k41ZQ5LY7uyQnw/edit).
Testcase also succeeds now:  `cargo test --features circom-2 groth16_proof_circom2`

### CODE REVIEW

**Comment by gakonst** [comment]
Wonder if @kobigurk has any time to take a look, because I haven't played with Circom2's witness generator yet.

Looks good otherwise in terms of code styling, don't forget to fmt/lint!

**Comment by kobigurk** [comment]
> Wonder if @kobigurk has any time to take a look, because I haven't played with Circom2's witness generator yet.
> 
> Should we add one more step on CI which runs the circom2 feature too?
> 
> Looks good otherwise in terms of code styling, don't forget to fmt/lint!

Unfortunately I'm not familiar yet either. Not sure when I will be!

**Comment by philsippl** [comment]
fmt and the broken test should be fixed now :)

re tests in ci: many tests are now failing (`cargo test --features circom-2`), because it tries to call the circom1 wasm with the circom2 features. I guess once the feature is less experimental, one could remove the feature flag and instead detect the version of the wasm by calling [`getVersion()`](https://docs.google.com/document/d/1P0j9zXjJRkhnyPT03VjxYBUySC8l4k41ZQ5LY7uyQnw/edit) and change the code path accordingly.

**Comment by gakonst** [comment]
SG - tracking in #14

**Comment by philsippl** [comment]
> SG - tracking in #15. think there's some lint fixes needed @philsippl

sorry @gakonst, missed a few clippy complains! I've also fixed a few others introduced by the circom2 changes and the ones referenced in #12 in a separate commit (with `#[allow(dead_code)]`, let me know if this is not desired).

**Comment by gakonst** [comment]
LGTM - thank you!

**Comment by oskarth** [comment]
Thanks @philsippl! Had some WIP branch for this but didn't have time to finish it up, beat me to it :)

> I guess once the feature is less experimental, one could remove the feature flag and instead detect the version of the wasm by calling getVersion() and change the code path accordingly.

Agree, that was my thinking as well.

**Pull request merged**
